# Generated by Django 2.2.6 on 2019-12-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='rating',
            new_name='main_rating',
        ),
        migrations.AddField(
            model_name='good',
            name='comments_numb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='good',
            name='img1',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='good',
            name='img2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='good',
            name='new_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='good',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
