# Generated by Django 2.2.6 on 2019-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_name', models.CharField(max_length=100)),
                ('editor_surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('count', models.IntegerField(max_length=10)),
                ('data_add', models.DateTimeField(verbose_name='data of add')),
                ('color', models.CharField(max_length=20)),
                ('year', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='QuantityOfViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_views', models.IntegerField()),
                ('link_to_hidden_ad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_surname', models.CharField(max_length=100)),
                ('user_dob', models.DateTimeField(verbose_name='date of birth')),
                ('user_mail', models.CharField(max_length=150)),
                ('user_male', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=100)),
            ],
        ),
    ]
